export const CityList = [
  { id: 1, name: 'Atlanta' },
  { id: 2, name: 'Boston' },
  { id: 3, name: 'Brooklyn' },
  { id: 4, name: 'Charlotte' },
  { id: 5, name: 'Chicago' },
  { id: 6, name: 'Cleveland' },
  { id: 7, name: 'Dallas' },
  { id: 8, name: 'Denver' },
  { id: 9, name: 'Detroit' },
  { id: 10, name: 'Golden State' },
  { id: 11, name: 'Houston' },
  { id: 12, name: 'Indiana' },
  { id: 13, name: 'Los Angeles' },
  { id: 15, name: 'Memphis ' },
  { id: 16, name: 'Miami ' },
  { id: 17, name: 'Milwaukee ' },
  { id: 18, name: 'Minnesota ' },
  { id: 19, name: 'New Orleans ' },
  { id: 20, name: 'New York ' },
  { id: 21, name: 'Oklahoma ' },
  { id: 22, name: 'Orlando ' },
  { id: 23, name: 'Philadelphia ' },
  { id: 24, name: 'Phoenix ' },
  { id: 25, name: 'Portland ' },
  { id: 26, name: 'Sacramento ' },
  { id: 27, name: 'San Antonio ' },
  { id: 28, name: 'Toronto ' },
  { id: 29, name: 'Utah ' },
  { id: 30, name: 'Washington' },
];